<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Search\Module'                          => __DIR__ . '/Module.php',
    'Search\Controller\SearchController'     => __DIR__ . '/src/Search/Controller/SearchController.php',
    'Search\Controller\TestController'       => __DIR__ . '/src/Search/Controller/TestController.php',
    'Search\Factory\ListingsTableFactory'    => __DIR__ . '/src/Search/Factory/ListingsTableFactory.php',
    'Search\Factory\SearchControllerFactory' => __DIR__ . '/src/Search/Factory/SearchControllerFactory.php',
    'Search\Filter\Float'                    => __DIR__ . '/src/Search/Filter/Float.php',
    'Search\Form\SearchForm'                 => __DIR__ . '/src/Search/Form/SearchForm.php',
    'Search\Form\SearchFormFilter'           => __DIR__ . '/src/Search/Form/SearchFormFilter.php',
    'Search\Model\ListingsTable'             => __DIR__ . '/src/Search/Model/ListingsTable.php',
    'SearchTest\Framework\TestCase'          => __DIR__ . '/tests/Search/Framework/TestCase.php',
    'ModuleTest'                             => __DIR__ . '/tests/Search/ModuleTest.php',
    'SearchTest\SampleTest'                  => __DIR__ . '/tests/Search/SampleTest.php',
);
